cc_binary(
    name = "exercise_1",
    srcs = ["main.cpp"],
    deps = [
        "//project/cli/circle",
        "//project/cli/rectangle",
    ],
    defines = [
        "CONFIG_CIRCLE",
        "CONFIG_RECTANGLE",
    ],
)
